### ISSUE TITLE
記事詳細画面でどんな機能が必要か考える

### ISSUE THREAD

**Issue by otomoringo** [btc2016Project/Prototype#2]
# 期限：5/12(木)

## 小野林くん
記事登録

**Comment by onobayashi** [comment]
プロトタイプを作るにあって現状で問題ありません。
すごくいいと思います。

今後追加するとしたらこんなんあったらいいのではという内容について
下記に数点記載します。(ぱって思いついた安易な発想なので要吟味!!!)

【追加機能】
・その人の記事への指標
　(例 　文量 : 少 ★★★☆☆ 多、  情報の新鮮度 :  古 ★☆☆☆☆ 新)
・(分類と被るかもですが)キーワードの入力
　(例　キーワード　： アメリカ、ITベンチャー、IoT )

【変更点】
・記事タイトルならびに記事URLのテキストボックスの文字数制限を
　もっと取った方がいいと思います

**Comment by aoyama8128** [comment]
小野林君
ありがとうございます！

記事への指標は分かりやすいし実装もそんなに難しくない気がして個人的にすごく賛成です。

タイトルとURLは完全に適当にとっていました。
特にURLはパラメータごと貼り付ける場合もあると思うのでもっととれるよう書き直したいと思います。
(機能的な設定はMaxlengthを設けるだけで平気だとおもうので、後々変更も可能だと思います)

**Comment by aoyama8128** [comment]
機能書き出し、画面定義に落とし込むことができました。
クローズします。
